# Generated by Django 5.1.7 on 2025-05-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
