# Generated by Django 5.1.7 on 2025-06-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_feedback_feedback_to_alter_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('is_email', models.BooleanField(default=False)),
                ('is_sms', models.BooleanField(default=False)),
            ],
        ),
    ]
