# Generated by Django 5.1.7 on 2025-06-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_modes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modes',
        ),
    ]
