# Generated by Django 5.1.7 on 2025-06-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_modes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
