# Generated by Django 5.1.7 on 2025-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_feedbacktype_question_feedback_feedbackresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
