# Generated by Django 5.1.7 on 2025-06-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_feedback_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=225)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
