# Generated by Django 5.1.7 on 2025-06-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_feedbackoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='options',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.feedbackoptions'),
            preserve_default=False,
        ),
    ]
