# Generated by Django 5.0.6 on 2024-07-29 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oss', '0005_alter_ae_assignment_ae_recommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Published_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on_date', models.DateField()),
                ('doi', models.CharField(max_length=255)),
                ('accepted_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.accepted_submission')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.journal')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl.volume'),
        ),
    ]
