# Generated by Django 5.1.7 on 2025-05-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0003_auto_20240806_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='published_article',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
