# Generated by Django 5.1.7 on 2025-05-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0004_published_article_area'),
        ('oss', '0014_alter_submission_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='published_article',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.specialization'),
        ),
    ]
