# Generated by Django 3.2.2 on 2024-07-26 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_status', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(max_length=50)),
                ('article_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('manuscript_id', models.CharField(blank=True, max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('is_funded', models.BooleanField(default=False)),
                ('no_of_figures', models.IntegerField(blank=True, null=True)),
                ('no_of_tables', models.IntegerField(blank=True, null=True)),
                ('no_of_words', models.IntegerField(blank=True, null=True)),
                ('is_submitted_already', models.BooleanField(default=False)),
                ('acknowledgement_1', models.BooleanField(default=False)),
                ('acknowledgement_2', models.BooleanField(default=False)),
                ('acknowledgement_3', models.BooleanField(default=False)),
                ('conflict_of_interest', models.BooleanField(default=False)),
                ('coi_describe', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('submitted_on', models.DateField(auto_now_add=True, null=True)),
                ('decissioned_on', models.DateField(auto_now_add=True, null=True)),
                ('is_decissioned', models.BooleanField(default=False)),
                ('final_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('admin_commments', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('article_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.article_status')),
                ('article_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.article_type')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.category')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.decision')),
                ('decision_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.journal')),
                ('parent_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent_submissions', to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_on', models.DateTimeField(blank=True, null=True)),
                ('accepted_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('review_recommendation', models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('MIN_R', 'Minimum Revision'), ('MAJ_R', 'Major Revision')], max_length=5)),
                ('review_comments', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('request_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.request_status')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.author')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('file_size', models.FloatField()),
                ('file_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.file_category')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer_Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.author')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer_Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_status', models.CharField(choices=[('R', 'Requested'), ('A', 'Accepted'), ('RJ', 'Reject')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('expiring_date', models.DateField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=225)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Journal_Editor_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.editor')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grant_number', models.CharField(max_length=50)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Correction_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_commments', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('detail', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='communications/')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
        migrations.CreateModel(
            name='AE_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ae_recommendation', models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('MIN_R', 'Minimum Revision'), ('MAJ_R', 'Major Revision')], max_length=5)),
                ('ae_comments', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accepted_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_file', models.FileField(upload_to='submissions/')),
                ('typeset_file', models.FileField(upload_to='submissions/')),
                ('corrected_title', models.CharField(blank=True, max_length=255, null=True)),
                ('corrected_abstract', models.TextField(blank=True, null=True)),
                ('corrected_on', models.DateField()),
                ('typeseted_on', models.DateField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss.submission')),
            ],
        ),
    ]
