# Generated by Django 3.2.2 on 2024-07-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accepted_submission',
            old_name='typeseted_on',
            new_name='typeset_on',
        ),
    ]
