# Generated by Django 3.2.2 on 2024-07-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0002_rename_typeseted_on_accepted_submission_typeset_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='admin_commments',
            new_name='admin_comments',
        ),
    ]
