# Generated by Django 5.0.6 on 2024-07-28 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0003_rename_admin_commments_submission_admin_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted_submission',
            name='corrected_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accepted_submission',
            name='typeset_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
