# Generated by Django 5.0.6 on 2024-07-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0004_alter_accepted_submission_corrected_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ae_assignment',
            name='ae_recommendation',
            field=models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('MIN_R', 'Minor Revision'), ('MAJ_R', 'Major Revision')], max_length=5),
        ),
        migrations.AlterField(
            model_name='submission',
            name='conflict_of_interest',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_funded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_submitted_already',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission_reviewer',
            name='review_recommendation',
            field=models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('MIN_R', 'Minor Revision'), ('MAJ_R', 'Major Revision')], max_length=5),
        ),
    ]
