# Generated by Django 5.0.6 on 2024-08-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0005_alter_ae_assignment_ae_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='revision_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='typeset_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
