# Generated by Django 5.0.6 on 2024-08-01 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0006_submission_revision_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_days_to_accept_invitation', models.IntegerField(blank=True, null=True)),
                ('due_days_to_review', models.IntegerField(blank=True, null=True)),
                ('due_days_to_minor_revision', models.IntegerField(blank=True, null=True)),
                ('due_days_to_major_revision', models.IntegerField(blank=True, null=True)),
                ('due_days_to_payment', models.IntegerField(blank=True, null=True)),
                ('due_days_to_corrections', models.IntegerField(blank=True, null=True)),
                ('due_days_to_typeset_approval', models.IntegerField(blank=True, null=True)),
                ('due_days_to_next_step', models.IntegerField(blank=True, null=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.journal')),
            ],
        ),
    ]
