# Generated by Django 3.2.2 on 2024-08-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0009_alter_submission_decision_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funder',
            name='grant_number',
        ),
        migrations.RemoveField(
            model_name='funder',
            name='name',
        ),
        migrations.AddField(
            model_name='funder',
            name='detail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
