# Generated by Django 5.1.7 on 2025-06-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0014_alter_submission_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.specialization'),
        ),
    ]
