# Generated by Django 5.1.7 on 2025-06-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0015_submission_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction_comments',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_comments', to='oss.submission'),
        ),
    ]
