# Generated by Django 5.1.7 on 2025-06-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0016_alter_correction_comments_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction_comments',
            name='additional_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
